name: JSON Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate JSON
        run: |
          for file in $(find . -name "*.json"); do
            if ! jq empty "$file" 2>/dev/null; then
              echo "❌ Invalid JSON in $file"
              exit 1
            fi
          done
          echo "✅ All JSON files are valid"
